### ISSUE TITLE
HttpClient instance created in com.yoelnunez.mobilefirst.analytics.AnalyticsAPI.java seems to be unused

### ISSUE THREAD

**Issue by laikabear** [ynunez/MobileFirstAnalyticsSender#1]
Hi Yoel,
Perhaps it is there for some future use, but in AnalyticsAPI you have the following in the createInstance method
        if (httpClient == null) {
            HttpClientBuilder builder = HttpClientBuilder.create()
                    .setMaxConnTotal(10);

            httpClient = builder.build();
        }

You provide a get/setHttpClient methods, but a grep of this project shows they are only used in the test code.

It appears to me that the meaningful HttpClient code is all in MobileFirstAnalyticsSender

John Graham

**Comment by ynunez** [comment]
Hi John,

Sorry for not responding sooner, but I just saw this issue. The point to have a setter for httpClient in this case is to let the user choose what http client they want to use. This project is not intended to be a standalone application therefore, having the option to choose an http client from their existing project is a good idea. By [default](https://github.com/ynunez/MobileFirstAnalyticsSender/blob/master/src/main/java/com/yoelnunez/mobilefirst/analytics/AnalyticsAPI.java#L40), an http client instance is set created but the user can override it as follows

```
HttpClient customHttpClient = new UserCustomHttpClient();
AnalyticsAPI.setHttpClient(customHttpClient);

AnalyticsAPI api = AnalyticsAPI.createInstance(appContext);
```

Regards,
Yoel Nunez
